name: Format Code

on:
  push:
    branches:
      - master # Adjust this to your default branch
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Specify your Python version

      - name: Install dependencies
        run: pip install black

      - name: Run Black and append output to file
        run: |
          # Create the file if it doesn't exist
          touch black_output.txt
          echo -e "\n$(black . --diff)" >> black_output.txt || true
          echo "Formatted output appended to black_output.txt"
